import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from './provider';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="ko" suppressHydrationWarning>
        <head>
            <ColorSchemeScript defaultColorScheme="auto" />
            <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no" />
        </head>
        <body className="bg-gray-100 dark:bg-gray-900 text-gray-900 dark:text-white">
        <Providers>
            <MantineProvider defaultColorScheme="auto" withCssVariables>
                {children}
            </MantineProvider>
        </Providers>
        </body>
        </html>
    );
}
